server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    active: ${CONFIG_PROFILE:git}
  cloud:
    config:
      server:
        native:
          search-locations: file:/config
          # search-locations: file:////home/iitzrohan/config
        git:
          uri: ${CONFIG_GIT_URI}
          default-label: main
          clone-on-start: true
          refresh-rate: 60

management:
  endpoints:
    web:
      exposure:
        include: "*"
